version: '3.8'

services:
  app:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    entrypoint: 'wait-for-it db:5432 --strict --'
    command: bash -c 'bundle exec rails server -b "0.0.0.0"'
    environment:
      - BUNDLE_PATH=/bundle/vendor
    ports:
      - '3000:3000'
    volumes:
      - ../../:/code
      - bundle:/bundle
    depends_on:
      - db

  db:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile-postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=password

volumes:
  bundle: {}
  postgres: {}
